
baseURL: 'https://ricard.dev./gists/'
languageCode: 'en-us'
title: "Ricard's code gists"
googleAnalytics: ""
disqusShortname: ""
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩
disableHugoGeneratorInject: true
pluralizeListTitles: false
pygmentsCodeFences: false
pygmentsUseClasses: false
minify: true
paginate: 9999
disableKinds:
  - section

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    noHl: false
    style: github
    tabWidth: 4

permalinks:
  writing: /:year-:month-:day/

params:
  description: "Collection of code snippets"

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed


